name: tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r autoref_lite/requirements.txt
      - run: pip install pytest
      - run: pytest -q || echo "No tests yet"
